### ISSUE TITLE
Каким образом делать множество порталов, если кнопок их вызывающих не одна, а больше. 

### ISSUE THREAD

**Issue by 1ncredibleM1nd** [YauhenKavalchuk/react-components#1]
Здравствуйте, с перва хочу поблагодарить Вас за Ваши объяснения, очень помогает в работе. 
Я реализовываю приложение , и встретилось такое. что на одной странице вызывается 5 разных модальных окон. Каким образом можно реализовывать модалки в таком случае ?

**Comment by YauhenKavalchuk** [comment]
Можно сделать одну основную обёртку Modal. А в качестве пропса передавать type. И на основании этого типа (type) рендерит содержимое модального окна

**Comment by YauhenKavalchuk** [comment]
Answered
